version: "3.3"
services:
  db:
    image: postgres:12
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
  
  backend:
    build:
      context: .
      dockerfile: docker/backend.dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./src:/app/
    depends_on:
      - db
    env_file:
      - .env

volumes:
  app-db-data: