"""empty message

Revision ID: 5f01c349a7d4
Revises: eabcdcf71e9b
Create Date: 2021-11-11 22:25:22.747871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f01c349a7d4'
down_revision = 'eabcdcf71e9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('title', sa.String(length=100), nullable=True))
    op.add_column('question', sa.Column('content', sa.String(length=255), nullable=True))
    op.drop_column('question', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('question', 'content')
    op.drop_column('question', 'title')
    # ### end Alembic commands ###
